# Generated by Django 5.2.6 on 2025-12-17 15:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GUI',
            fields=[
                ('id_gui', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_atribut', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_user', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_user', models.CharField(max_length=100)),
                ('email_user', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SqlTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('ref_column_name', models.CharField(max_length=255)),
                ('ref_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='main.importedtable')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_keys', to='main.importedtable')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main.importedtable')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.gui')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('gui', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_project', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(blank=True, max_length=100)),
                ('tanggal_project_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_akses_terakhir', models.DateTimeField(default=django.utils.timezone.now)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.pengguna')),
            ],
        ),
        migrations.AddField(
            model_name='gui',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guis', to='main.project'),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='SqlColumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('datatype', models.CharField(max_length=50)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main.sqltable')),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id_usecase', models.AutoField(primary_key=True, serialize=False)),
                ('hasil_usecase', models.ImageField(upload_to='usecases/')),
                ('plantuml_code', models.TextField(blank=True, null=True)),
                ('gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecases', to='main.gui')),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseSpecification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_name', models.CharField(default='Feature', max_length=255)),
                ('summary_description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('Must Have', 'Must Have'), ('Should Have', 'Should Have'), ('Could Have', 'Could Have'), ("Won't Have", "Won't Have")], default='Must Have', max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('input_precondition', models.TextField(blank=True, null=True)),
                ('input_postcondition', models.TextField(blank=True, null=True)),
                ('gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='main.gui')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('actor_action', models.TextField(blank=True, null=True)),
                ('system_response', models.TextField(blank=True, null=True)),
                ('usecase_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_paths', to='main.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('actor_action', models.TextField(blank=True, null=True)),
                ('system_response', models.TextField(blank=True, null=True)),
                ('usecase_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_paths', to='main.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='AlternativePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('actor_action', models.TextField(blank=True, null=True)),
                ('system_response', models.TextField(blank=True, null=True)),
                ('usecase_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_paths', to='main.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plantuml_code', models.TextField(blank=True, default='')),
                ('diagram_image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('use_case_spec', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_diagram', to='main.usecasespecification')),
            ],
            options={
                'verbose_name': 'Activity Diagram',
                'verbose_name_plural': 'Activity Diagrams',
            },
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id_userstory', models.AutoField(primary_key=True, serialize=False)),
                ('input_sebagai', models.CharField(max_length=100)),
                ('input_fitur', models.CharField(max_length=100)),
                ('input_tujuan', models.CharField(blank=True, max_length=255, null=True)),
                ('gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstories', to='main.gui')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id_sequence', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('input_actor', models.TextField()),
                ('input_boundary', models.TextField()),
                ('input_controller', models.TextField()),
                ('input_entity', models.TextField()),
                ('hasil_sequence', models.ImageField(upload_to='sequences/')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='main.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDiagram',
            fields=[
                ('id_classdiagram', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('script_classdiagram', models.TextField()),
                ('hasil_classdiagram', models.ImageField(upload_to='class_diagrams/')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_diagrams', to='main.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryScenario',
            fields=[
                ('id_scenario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_scenario', models.TextField()),
                ('input_given', models.TextField()),
                ('input_when', models.TextField()),
                ('input_then', models.TextField()),
                ('input_and', models.TextField()),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='main.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('input_type', models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('textarea', 'Textarea')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('element_type', models.CharField(default='text', max_length=50)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='main.page')),
            ],
            options={
                'db_table': 'main_inputelement',
                'unique_together': {('page', 'order')},
            },
        ),
    ]
