# Generated by Django 5.2.6 on 2025-10-25 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_user', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_user', models.CharField(max_length=100)),
                ('email_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_project', models.CharField(max_length=100)),
                ('deskripsi', models.CharField(blank=True, max_length=100)),
                ('tanggal_project_dibuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanggal_akses_terakhir', models.DateTimeField(default=django.utils.timezone.now)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='GUI',
            fields=[
                ('id_gui', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_atribut', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guis', to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id_session', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('login_time', models.DateTimeField()),
                ('logout_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Usecase',
            fields=[
                ('id_usecase', models.AutoField(primary_key=True, serialize=False)),
                ('hasil_usecase', models.ImageField(upload_to='usecases/')),
                ('gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usecases', to='main.gui')),
            ],
        ),
        migrations.CreateModel(
            name='UseCaseSpecification',
            fields=[
                ('id_usecasespecification', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('hasil_usecasespecification', models.ImageField(upload_to='usecase_specs/')),
                ('input_precondition', models.TextField()),
                ('input_postcondition', models.TextField()),
                ('usecase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='main.usecase')),
            ],
        ),
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id_userstory', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('input_sebagai', models.CharField(max_length=100)),
                ('input_fitur', models.CharField(max_length=100)),
                ('gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstories', to='main.gui')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id_sequence', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('input_actor', models.TextField()),
                ('input_boundary', models.TextField()),
                ('input_controller', models.TextField()),
                ('input_entity', models.TextField()),
                ('hasil_sequence', models.ImageField(upload_to='sequences/')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='main.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='ClassDiagram',
            fields=[
                ('id_classdiagram', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('script_classdiagram', models.TextField()),
                ('hasil_classdiagram', models.ImageField(upload_to='class_diagrams/')),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_diagrams', to='main.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='UserStoryScenario',
            fields=[
                ('id_scenario', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama_scenario', models.TextField()),
                ('input_given', models.TextField()),
                ('input_when', models.TextField()),
                ('input_then', models.TextField()),
                ('input_and', models.TextField()),
                ('userstory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='main.userstory')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityDiagram',
            fields=[
                ('id_activity', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('script_activity', models.TextField()),
                ('nama_usecase', models.TextField()),
                ('main_flow', models.TextField()),
                ('alternative_flow', models.TextField()),
                ('hasil_activity', models.ImageField(upload_to='activities/')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='main.userstoryscenario')),
            ],
        ),
    ]
