# Generated by Django 5.2.6 on 2026-07-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testscenario',
            name='scenario_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Alternative', 'Alternative'), ('Exception', 'Exception'), ('Positive', 'Positive'), ('Negative', 'Negative')], max_length=20),
        ),
    ]
