# Generated by Django 5.2.7 on 2025-11-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$xxxxx', max_length=255),
            preserve_default=False,
        ),
    ]
