# Generated by Django 5.2.7 on 2025-11-03 05:20

from django.db import migrations, models
from django.contrib.auth.hashers import make_password


def add_dummy_data(apps, schema_editor):
    Pengguna = apps.get_model('main', 'Pengguna')
    
    Pengguna.objects.create(
        id_user='U0001',
        nama_user='Kelompok1',
        email_user='kelompok1@gmail.com',
        password=make_password('kelompok1')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$xxxxx', max_length=255),
            preserve_default=False,
        ),
        migrations.RunPython(add_dummy_data),
    ]
    