# Generated by Django 5.2.16 on 2026-07-23 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_testscenario_scenario_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedtable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_tables', to='main.project'),
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='use_case_specs', to='main.project'),
        ),
        migrations.AlterField(
            model_name='importedtable',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='importedtable',
            unique_together={('project', 'name')},
        ),
    ]
