# Generated by Django 5.2.6 on 2025-12-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userstory_input_tujuan'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='plantuml_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
