# Generated by Django 5.2.8 on 2025-11-10 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pengguna_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='email_user',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImportedRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=255)),
                ('ref_column_name', models.CharField(max_length=255)),
                ('ref_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referenced_by', to='main.importedtable')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_keys', to='main.importedtable')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='main.importedtable')),
            ],
        ),
    ]
