# Generated by Django 5.2.6 on 2025-12-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usecasespecification_gui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='gui',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.gui'),
        ),
    ]
