# Generated by Django 5.2.16 on 2026-07-24 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_importedtable_project_usecasespecification_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.project'),
        ),
        migrations.AddField(
            model_name='sqltable',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sql_tables', to='main.project'),
        ),
        migrations.AddField(
            model_name='userstory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='main.project'),
        ),
    ]
