# Generated by Django 5.2.6 on 2025-12-18 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userstory_gui'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_type', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=20)),
                ('use_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='main.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='TestStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('condition', models.CharField(max_length=50)),
                ('action_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('target_text', models.CharField(blank=True, max_length=255, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='main.testscenario')),
            ],
        ),
    ]
