# Generated by Django 5.2.16 on 2026-07-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_fix_data_isolation_project_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gui',
            name='id_gui',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='feature',
            constraint=models.UniqueConstraint(fields=('project', 'nama'), name='unique_feature_per_project'),
        ),
        migrations.AddConstraint(
            model_name='gui',
            constraint=models.UniqueConstraint(fields=('project',), name='unique_gui_per_project'),
        ),
        migrations.AddConstraint(
            model_name='usecasespecification',
            constraint=models.UniqueConstraint(fields=('project', 'feature_name'), name='unique_spec_per_project'),
        ),
        migrations.AddConstraint(
            model_name='userstory',
            constraint=models.UniqueConstraint(fields=('project', 'input_sebagai', 'input_fitur'), name='unique_userstory_per_project'),
        ),
    ]
