# Generated by Django 5.2.6 on 2025-12-20 09:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_testscenario_teststep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_project',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
