# Generated by Django 5.2.6 on 2025-12-12 14:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sqltable_sqlcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activitydiagram',
            options={'verbose_name': 'Activity Diagram', 'verbose_name_plural': 'Activity Diagrams'},
        ),
        migrations.RemoveField(
            model_name='activitydiagram',
            name='alternative_flow',
        ),
        migrations.RemoveField(
            model_name='activitydiagram',
            name='hasil_activity',
        ),
        migrations.RemoveField(
            model_name='activitydiagram',
            name='id_activity',
        ),
        migrations.RemoveField(
            model_name='activitydiagram',
            name='main_flow',
        ),
        migrations.RemoveField(
            model_name='activitydiagram',
            name='nama_usecase',
        ),
        migrations.RemoveField(
            model_name='activitydiagram',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='activitydiagram',
            name='script_activity',
        ),
        migrations.AddField(
            model_name='activitydiagram',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='activitydiagram',
            name='diagram_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitydiagram',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='activitydiagram',
            name='plantuml_code',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activitydiagram',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='activitydiagram',
            name='use_case_spec',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_diagram', to='main.usecasespecification'),
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='priority',
            field=models.CharField(choices=[('Must Have', 'Must Have'), ('Should Have', 'Should Have'), ('Could Have', 'Could Have'), ("Won't Have", "Won't Have")], default='Must Have', max_length=250),
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=250),
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='summary_description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usecasespecification',
            name='input_postcondition',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usecasespecification',
            name='input_precondition',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='id_userstory',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AlternativePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_basic_step', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('usecase_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_paths', to='main.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='BasicPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('usecase_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_paths', to='main.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_basic_step', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('usecase_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exception_paths', to='main.usecasespecification')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('gui', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='main.gui')),
            ],
            options={
                'unique_together': {('gui', 'order')},
            },
        ),
        migrations.CreateModel(
    name='Element',
    fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('name', models.CharField(max_length=255)),
        ('input_type', models.CharField(
            choices=[
                ('text', 'Text'), 
                ('number', 'Number'), 
                ('email', 'Email'), 
                ('password', 'Password'), 
                ('date', 'Date'), 
                ('checkbox', 'Checkbox'), 
                ('radio', 'Radio'), 
                ('textarea', 'Textarea')
            ], 
            max_length=20
        )),
        ('order', models.PositiveIntegerField()),
        ('page', models.ForeignKey(
            on_delete=django.db.models.deletion.CASCADE, 
            related_name='elements', 
            to='main.page'
        )),
    ],
    options={
        'unique_together': {('page', 'order')},
    },
),
]
