# Generated by Django 5.2.6 on 2025-12-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feature_alter_activitydiagram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='user_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usecases', to='main.userstory'),
        ),
    ]
