# Generated by Django 5.2.16 on 2026-07-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_add_db_constraints_and_gui_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscenario',
            name='scenario_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
