# Generated by Django 5.2.6 on 2025-12-15 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_feature_alter_activitydiagram_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tanggal_akses_terakhir',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tanggal_project_dibuat',
        ),
        migrations.AddField(
            model_name='project',
            name='tanggal_dibuat',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tanggal_terakhir_diakses',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
    ]
