# Generated by Django 5.2.6 on 2025-12-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_project_id_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id_project',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
