# Generated by Django 5.2.16 on 2026-07-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_testscenario_scenario_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecasespecification',
            name='sequence_config_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usecasespecification',
            name='sequence_plantuml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
