# Generated by Django 5.2.6 on 2025-12-16 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_project_tanggal_akses_terakhir_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='tanggal_dibuat',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tanggal_terakhir_diakses',
        ),
        migrations.AddField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('button', 'Button'), ('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('radio', 'Radio'), ('textarea', 'Textarea')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='tanggal_akses_terakhir',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='tanggal_project_dibuat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='element',
            name='input_type',
        ),
    ]
