# Generated by Django 5.2.16 on 2026-07-31 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_usecasespecification_sequence_config_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternativepath',
            name='from_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='alternativepath',
            name='group_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exceptionpath',
            name='from_step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exceptionpath',
            name='group_index',
            field=models.IntegerField(default=0),
        ),
    ]
